### PR TITLE
Removed orogen/maps (now in dfki-ric)

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Comment by planthaber** [comment]
Is there another package_set to add here that contains slam/maps, this change will definately break this package set, as slam/maps  is a dependency, but undefined.

**Comment by skasperski** [comment]
You mean slam/orogen/maps, right? Which package depends on it?

**Comment by planthaber** [comment]
At least the "old" ones, but:
envire/envire_maps
envire/orogen/envire_maps
slam/orogen/maps
envire-orogen-envire_exporters
envire-envire_collider_mls

**Comment by skasperski** [comment]
I don't think so, I never realized that this package existed until I tried to create one with that name. The first 3 don't need it, gonna check the last 2 as I never used them before.

Update: As far as I can tell, none of these uses slam/orogen/maps.

**Pull request merged**
