### PR TITLE
Switch to using original ogdf repository

### PR DESCRIPTION
**Pull request by 2maz**

### CODE REVIEW

**Comment by Rauldg** [comment]
I will test this using the [buildconf from envire](https://github.com/envire/buildconf) or do you have a better suggestion?

**Comment by 2maz** [comment]
Sure, but that is up to you, as long as you do not have an override in that buildconf.

ogdf/ogdf master already merged my fix that I required for the debian packaging. So I expect no issues in building.

**Comment by Rauldg** [comment]
> Sure, but that is up to you, as long as you do not have an override in that buildconf.

Yes, I will try the buildconf with an override on the package set to your branch. 

If that works, I am up for the merge

**Comment by Rauldg** [comment]
Between the two versions of OGDF (Arne's and official) there are several differences some are unnecessary but others might bring problems.

ogdf_branches

For instance we have [this bugfix](https://github.com/arneboe/ogdf/commit/625a918c0014d115e77f1acf5efa43f22f0cff7a) from @arneboe

**Comment by arneboe** [comment]
My memory is very vague but afair:
"array subscript is above array bounds " is a warning, not an error. ogdf was build with -WError thus all warnings became errors.
The old gcc version on ubuntu 14.04 had a bug that falsely triggered this warning.
This "bugfix" avoids that gcc bug. 

Probably this is no longer required and can be removed.

**Comment by arneboe** [comment]
If I remember correctly the whole reason for this fork was ubuntu 14 compatibility...

**Comment by 2maz** [comment]
I agree, that does not look critical to me - especially since building the debian packages ran fine.
Anyhow, if there are critical issues identified at later stages, IMO fixes should be merged into the original repo of ogdf.

**Comment by Rauldg** [comment]
For what I have checked the core library builds fine with the changes from @2maz 

The tests are not building for some link error with class_loader, which seems unrelated.

**Pull request merged**
